### ISSUE TITLE
origin?

### ISSUE THREAD

**Issue by albertocsm** [saraivinha85/plugin.video.tugaio#1]
is this the source of the current Tug.io addon (tugaio-repository.xsteal-0.0.1.zip) made by Eduardo Pires?

**Comment by saraivinha85** [comment]
Hello,

No, it's my own implementation.

Kind regards,

Pedro Saraiva

2015-10-07 11:35 GMT+01:00 Alberto São Marcos notifications@github.com:

**Comment by whitecoder010** [comment]
Olá Saraivinha, este addon esta funcional ? 
Não o consigo instalar, não sei porque. 
Obrigado

**Comment by saraivinha85** [comment]
Olá. Experimenta copiar a pasta tugaio para dentro da pasta addons do kodi.
Neste momento parece que os links dos filmes já mudaram outra vez desde ontem e não está a funcionar. No entanto, os links das series parecem funcionar.

**Comment by saraivinha85** [comment]
Ok, já está tudo a funcionar outra vez :)
